# These are supported funding model platforms

# github: YunYouJun # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: YunYouJun # Replace with a single Patreon username
ko_fi: sakurayumine
custom: https://sponsors-yumine.netlify.app # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']