// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppContainer: typeof import('./src/components/AppContainer.vue')['default']
    ImageDetail: typeof import('./src/components/ImageDetail.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
  }
}

export {}
